### PR TITLE
Fix build failures with GCC 15

### PR DESCRIPTION
**Pull request by disgoel**
On newer toolchains, filebench fails to compile because flowop callback pointers in flowop.h use old-style unprototyped declarations, leading to errors such as:
  too many arguments to function ‘flowop->fo_init’
  too many arguments to function ‘flowop->fo_func’

Second, vars.h/vars.c use "bool" as a parameter name in boolean helper functions. On modern compilers/language modes this causes parse failures such as:
  error: two or more data types in declaration specifiers

Update the flowop callback declarations to use explicit typed prototypes, and rename the boolean helper parameter from "bool" to "bval".

These changes restore successful build on Linux with GCC 15.2.0.

### CODE REVIEW

**Comment by disgoel** [comment]
@sectorsize512 can you please review
